# Generated by Django 5.2.17 on 2026-10-02 09:55

import uuid

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models

import accounts.managers

DISPLAY_NAME_TRIGGER_SQL = """
CREATE OR REPLACE FUNCTION trigger_auto_generate_display_name()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.display_name IS NULL OR NEW.display_name = '' THEN
            NEW.display_name := trim(concat(NEW.last_name, ' ', NEW.first_name));
        END IF;
        IF NEW.display_name IS NULL OR NEW.display_name = '' THEN
            NEW.display_name := 'Thành viên UTask';
        END IF;
        RETURN NEW;
    END IF;
    IF NEW.display_name IS NULL OR NEW.display_name = ''
       OR NEW.first_name IS DISTINCT FROM OLD.first_name
       OR NEW.last_name IS DISTINCT FROM OLD.last_name THEN
        NEW.display_name := trim(concat(NEW.last_name, ' ', NEW.first_name));
        IF NEW.display_name = '' THEN
            NEW.display_name := 'Thành viên UTask';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_user_profile_display_name
BEFORE INSERT OR UPDATE ON user_profiles
FOR EACH ROW EXECUTE FUNCTION trigger_auto_generate_display_name();
"""

DROP_DISPLAY_NAME_TRIGGER_SQL = """
DROP TRIGGER IF EXISTS trg_user_profile_display_name ON user_profiles;
DROP FUNCTION IF EXISTS trigger_auto_generate_display_name();
"""


def seed_global_roles(apps, schema_editor):
    GlobalRole = apps.get_model("accounts", "GlobalRole")
    database = schema_editor.connection.alias
    roles = (
        (
            "SYSTEM_ADMIN",
            "Quản trị viên Hệ thống",
            "Quản trị Identity; không thay thế quyền sở hữu tài nguyên của service khác.",
        ),
        (
            "TEACHER",
            "Giảng viên",
            "Vai trò toàn cục cho giảng viên; quyền trên lớp do Classroom quản lý.",
        ),
        (
            "STUDENT",
            "Sinh viên",
            "Vai trò toàn cục cho sinh viên; ghi danh lớp do Classroom quản lý.",
        ),
    )
    for code, name, description in roles:
        GlobalRole.objects.using(database).get_or_create(
            code=code,
            defaults={"name": name, "description": description},
        )


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=255)),
                ("username", models.CharField(max_length=100)),
                (
                    "password",
                    models.CharField(db_column="password_hash", max_length=255),
                ),
                (
                    "last_login",
                    models.DateTimeField(blank=True, db_column="last_login_at", null=True),
                ),
                ("student_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "account_status",
                    models.CharField(
                        choices=[
                            ("PENDING_ACTIVATION", "Pending activation"),
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("LOCKED", "Locked"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("is_email_verified", models.BooleanField(default=False)),
                ("failed_login_attempts", models.IntegerField(default=0)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                (
                    "last_login_ip",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "users",
                "indexes": [
                    models.Index(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=["account_status"],
                        name="idx_users_account_status",
                    ),
                    models.Index(
                        condition=models.Q(("locked_until__isnull", False)),
                        fields=["locked_until"],
                        name="idx_users_locked_until",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("email",), name="uq_users_email"),
                    models.UniqueConstraint(fields=("username",), name="uq_users_username"),
                    models.UniqueConstraint(
                        condition=models.Q(("student_id__isnull", False)),
                        fields=("student_id",),
                        name="uq_users_student_id",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "account_status__in",
                                ["PENDING_ACTIVATION", "ACTIVE", "SUSPENDED", "LOCKED"],
                            )
                        ),
                        name="chk_user_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("failed_login_attempts__gte", 0)),
                        name="chk_login_attempts",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("account_status", "LOCKED"),
                                ("locked_until__isnull", False),
                            ),
                            models.Q(
                                models.Q(("account_status", "LOCKED"), _negated=True),
                                ("locked_until__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="chk_user_lock_state",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "email",
                                django.db.models.functions.text.Lower(
                                    django.db.models.functions.text.Trim(models.F("email"))
                                ),
                            ),
                            models.Q(("email", ""), _negated=True),
                        ),
                        name="chk_user_email_normalized",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "username",
                                django.db.models.functions.text.Lower(
                                    django.db.models.functions.text.Trim(models.F("username"))
                                ),
                            ),
                            models.Q(("username", ""), _negated=True),
                        ),
                        name="chk_user_username_normalized",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("student_id__isnull", True),
                            models.Q(
                                (
                                    "student_id",
                                    django.db.models.functions.text.Upper(
                                        django.db.models.functions.text.Trim(models.F("student_id"))
                                    ),
                                ),
                                models.Q(("student_id", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="chk_user_student_id_normalized",
                    ),
                ],
            },
            managers=[
                ("objects", accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="GlobalRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("SYSTEM_ADMIN", "System administrator"),
                            ("TEACHER", "Teacher"),
                            ("STUDENT", "Student"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "global_roles",
                "constraints": [
                    models.UniqueConstraint(fields=("code",), name="uq_global_roles_code"),
                    models.CheckConstraint(
                        condition=models.Q(("code__in", ["SYSTEM_ADMIN", "TEACHER", "STUDENT"])),
                        name="chk_global_role_code",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(default="", max_length=100)),
                ("last_name", models.CharField(default="", max_length=100)),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("avatar_url", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "github_username",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "academic_year",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "faculty",
                    models.CharField(blank=True, default="CNTT", max_length=100, null=True),
                ),
                (
                    "timezone",
                    models.CharField(default="Asia/Ho_Chi_Minh", max_length=50),
                ),
                ("preferences", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "db_table": "user_profiles",
                "indexes": [
                    models.Index(
                        django.db.models.functions.text.Lower("github_username"),
                        condition=models.Q(("github_username__isnull", False)),
                        name="idx_profiles_github_user",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserGlobalRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by_user",
                    models.ForeignKey(
                        blank=True,
                        db_column="assigned_by_user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_global_roles",
                        to="accounts.user",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        db_column="role_id",
                        db_index=False,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="user_assignments",
                        to="accounts.globalrole",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="global_role_assignments",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "db_table": "user_global_roles",
                "indexes": [models.Index(fields=["role"], name="idx_user_global_roles_role_id")],
                "constraints": [
                    models.UniqueConstraint(fields=("user", "role"), name="uq_user_global_role")
                ],
            },
        ),
        migrations.RunSQL(
            sql=DISPLAY_NAME_TRIGGER_SQL,
            reverse_sql=DROP_DISPLAY_NAME_TRIGGER_SQL,
        ),
        migrations.RunPython(seed_global_roles, migrations.RunPython.noop),
    ]
