# Generated by Django 5.2.17 on 2026-10-02 14:17

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actor_id", models.CharField(blank=True, max_length=100, null=True)),
                ("action", models.CharField(max_length=60)),
                (
                    "target_user_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ip_address", models.CharField(max_length=45)),
                ("user_agent", models.TextField()),
                ("details", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "audit_logs",
                "indexes": [
                    models.Index(fields=["-created_at"], name="idx_audit_logs_created_at"),
                    models.Index(
                        condition=models.Q(("target_user_id__isnull", False)),
                        fields=["target_user_id", "-created_at"],
                        name="idx_audit_logs_target_user",
                    ),
                    models.Index(
                        condition=models.Q(("actor_id__isnull", False)),
                        fields=["actor_id", "-created_at"],
                        name="idx_audit_logs_actor",
                    ),
                    models.Index(fields=["action", "-created_at"], name="idx_audit_logs_action"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token_family", models.UUIDField()),
                ("refresh_token_hash", models.CharField(max_length=64)),
                ("is_revoked", models.BooleanField(default=False)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revoked_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOGOUT", "Logout"),
                            ("LOGOUT_ALL", "Logout all sessions"),
                            ("ROTATED", "Refresh token rotated"),
                            ("REPLAY_ATTACK", "Refresh token replay detected"),
                            ("ADMIN_REVOKED", "Revoked by administrator"),
                            ("PASSWORD_CHANGED", "Password changed"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("ip_address", models.CharField(max_length=45)),
                ("user_agent", models.TextField()),
                (
                    "device_name",
                    models.CharField(default="Unknown Device", max_length=100),
                ),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "db_table": "user_sessions",
                "indexes": [
                    models.Index(
                        fields=["user", "is_revoked", "expires_at"],
                        name="idx_sessions_user_active",
                    ),
                    models.Index(fields=["token_family"], name="idx_sessions_token_family"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("refresh_token_hash",),
                        name="uq_sessions_refresh_token_hash",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_revoked", False)),
                        fields=("token_family",),
                        name="uq_session_family_live",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("expires_at__gt", models.F("created_at"))),
                        name="chk_session_expiry",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("is_revoked", True),
                                ("revoked_at__isnull", False),
                                ("revoked_reason__isnull", False),
                            ),
                            models.Q(
                                ("is_revoked", False),
                                ("revoked_at__isnull", True),
                                ("revoked_reason__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="chk_session_revocation",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("revoked_reason__isnull", True),
                            (
                                "revoked_reason__in",
                                [
                                    "LOGOUT",
                                    "LOGOUT_ALL",
                                    "ROTATED",
                                    "REPLAY_ATTACK",
                                    "ADMIN_REVOKED",
                                    "PASSWORD_CHANGED",
                                ],
                            ),
                            _connector="OR",
                        ),
                        name="chk_session_revoked_reason",
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            sql=(
                "CREATE OR REPLACE FUNCTION trigger_prevent_audit_log_modification() "
                "RETURNS TRIGGER AS $$ "
                "BEGIN "
                "RAISE EXCEPTION 'Audit logs are immutable. UPDATE or DELETE "
                "operations are strictly prohibited.'; "
                "END; "
                "$$ LANGUAGE plpgsql;",
                "CREATE TRIGGER trg_audit_logs_immutable "
                "BEFORE UPDATE OR DELETE ON audit_logs "
                "FOR EACH ROW EXECUTE FUNCTION trigger_prevent_audit_log_modification();",
            ),
            reverse_sql=(
                "DROP TRIGGER IF EXISTS trg_audit_logs_immutable ON audit_logs;",
                "DROP FUNCTION IF EXISTS trigger_prevent_audit_log_modification();",
            ),
        ),
    ]
