# Generated by Django 5.2.17 on 2026-10-02 18:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_sessions_and_audit"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersession",
            name="refresh_jti",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("aggregate_id", models.UUIDField()),
                ("event_type", models.CharField(max_length=100)),
                ("event_version", models.PositiveIntegerField(default=1)),
                ("data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "outbox_events",
                "indexes": [
                    models.Index(
                        condition=models.Q(("published_at__isnull", True)),
                        fields=["created_at"],
                        name="idx_identity_outbox_pending",
                    )
                ],
            },
        ),
    ]
