# Generated by Django 5.2.17 on 2026-10-03 10:26

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_library_auth"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(max_length=100)),
                ("endpoint_path", models.CharField(max_length=255)),
                ("idempotency_key", models.CharField(max_length=100)),
                ("payload_hash", models.CharField(max_length=64)),
                ("response_status", models.PositiveSmallIntegerField()),
                ("response_body", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "idempotency_records",
                "indexes": [models.Index(fields=["created_at"], name="idx_idempotency_created_at")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_id", "endpoint_path", "idempotency_key"),
                        name="uq_identity_idempotency_scope",
                    )
                ],
            },
        ),
    ]
